---
title: "By catch estimation"
author: "Jae S. Choi"
toc: true
number-sections: true
highlight-style: pygments
format:
  html: 
    code-fold: true
    html-math-method: katex
  pdf:
    geometry: 
      - top=30mm
      - left=30mm
  docx: default 
---

# Approach: estimate bycatch from at seas observed data and project onto marfis data

First set up environment.

```{r}
#| eval: true
#| output: false

    # Get data and format based upon parameters:

    year.assessment = 2023
    p = bio.snowcrab::load.environment( year.assessment=year.assessment )
    loadfunctions( "aegis")
    loadfunctions( "bio.snowcrab")

    require(ggplot2)
    require(data.table)
 
    bycatch_dir = file.path( p$annual.results, "bycatch")
    
    years = as.character(1996: year.assessment)
    
    # Prepare at sea observed data 
    # obs = observer.db( DS="bycatch_clean_data", p=p,  yrs=p$yrs )  


```


## Naive estimation: directly from observations

We estimate bycatch using at-sea-observed catch rate estimates and re-scaling these naively to total snow crab fishery effort: 

```{r}
# look at efficiency of snow crab capture vs snow crab sdiscard (soft-shelled, sublegal or female crab):
  region="cfaall"
  region="cfanorth"
  region="cfasouth"
  region="cfa4x"
  
    o = observer.db( DS="bycatch_summary", p=p,  yrs=p$yrs, region=region )   
    

    dev.new(width=8, height=6)
    pl = ggplot( o$eff_summ, aes(x=fishyr, y=loss, ymin=loss-losssd, ymax=loss+losssd) ) +
      geom_pointrange()  + # Vertical line with point in the middle
      geom_errorbar(width = 0.1, col="brown") + # Standard error bars
      geom_point(size = 1.5, col="darkred") +
      labs(x="Year", y="Discard rate of snow crab (At sea observed, by weight)" )
    (pl)

  
    # compare catch rates
    dev.new(width=10, height=length(o$spec)/2 )  
    plot( o$spec ~ o$bct, xlab = "At sea observed catch rate in snow crab fishery (kg/trap)", ylab="Species", type="p", cex=1.5, pch=19, col="darkorange", xlim=c(0, max(o$bct, na.rm=TRUE)*1.25), yaxt="n" )  
    text( o$bct, o$spec,  labels=o$species, pos=4, srt=0 , cex=1, col="darkslateblue")
    text( max(o$bct, na.rm=TRUE)*0.75, 1, labels=paste( "Snow crab CPUE (At sea obs., mean): ", o$bct_sc, " kg/trap"), col="darkred", cex=1.5 )



    print( o$bycatch_table )
    # write.csv( o$bycatch_table, file="tmp.csv")  # if you need to save it

```


--- END ---
